deploy-contract:
	forge create --rpc-url https://rpc.sepolia-api.lisk.com --etherscan-api-key MVUSE7NIRPDNPHMS6YQZETVJAYP12FDBMH --verify --verifier blockscout --verifier-url https://sepolia-blockscout.lisk.com/api --private-key 43db3940e393854a1b3a267e7a9f0dc1a0d7ffabe28d14a12b5010a2949a3e6b  --broadcast src/CommodityPool.sol:CommodityPool --constructor-args "0x4c8d4Ff2Ce701c39ebAd75b7d1bE1c103a4B1aD4" 1000 30


# forge verify-contract 0x7E325d1E7E568bc95a37FD1dc54777F482A83A75 \
# ./src/CommodityPool.sol:CommodityPool \
# --chain 4202 \
# --watch \
# --verifier blockscout \
# --verifier-url https://sepolia-blockscout.lisk.com/api

# deploy-token:
# forge create --rpc-url https://rpc.sepolia-api.lisk.com \
# --etherscan-api-key MVUSE7NIRPDNPHMS6YQZETVJAYP12FDBMH \
# --verify \
# --verifier blockscout \
# --verifier-url https://sepolia-blockscout.lisk.com/api \
# --private-key 43db3940e393854a1b3a267e7a9f0dc1a0d7ffabe28d14a12b5010a2949a3e6b  \
# src/femfundToken.sol:femfundToken


# verify-token:
# forge verify-contract 0x4c8d4Ff2Ce701c39ebAd75b7d1bE1c103a4B1aD4 \
# ./src/femfundToken.sol:femfundToken \
# --chain 4202 \
# --watch \
# --verifier blockscout \
# --verifier-url https://sepolia-blockscout.lisk.com/api